### ISSUE TITLE
Playing YouTube links doesn't work

### ISSUE THREAD

**Issue by qStivi** [qStivi/DerBot#25]
**Describe the bug**
When trying to play a YouTube playlist the bot crashes with a JSONExeption

**To Reproduce**
1. Enter `/play [youtube playlist link]` 

**Expected behavior**
The bot plays songs from the playlist.

**Screenshots**
![image](https://user-images.githubusercontent.com/40562298/117200010-33a05f00-adeb-11eb-9d12-5b2253bbeb41.png)

**Comment by qStivi** [comment]
Fix `/play` in general...

**Comment by LenHukiro** [comment]
The formatting in CommandManager on line 81:
str = str.replaceAll("[^a-z0-9A-Z -]", ""); 
causes the link to be invalid and be taken as a search request, when a link was sent.
Either the formatting should be adjusted or the Request Type in PlayCommand should return the correct format.
