### ISSUE TITLE
Create roles if they do not exist

### ISSUE THREAD

**Issue by qStivi** [qStivi/DerBot#47]
When want to add the bot to a new server you have to create all roles manually. It would be great if the bot would do that automatically.

**Comment by qStivi** [comment]
Related to #45

**Comment by LenHukiro** [comment]
Done with creating the roles, if they dont exist.
Currently on moving emotes to a file so they can be replaced if the bot doesnt have access to them.

**Comment by LenHukiro** [comment]
Currently focusing on some work stuff, will resume with it prob on the weekend if i have time or in 2 weeks.
